// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package hunter

// An arrow as the client's items describe it: the damage per second it adds to a bow or crossbow,
// ItemDamageAmmo's value for its item level and quality rounded down to the half point, as the
// tooltip reads it.
type generatedArrow struct {
	Name   string
	ItemID int32
	DPS    float64
}

// Keyed by the arrow's Go identifier, which is what proto.HunterOptions_Ammo names it.
var arrows = map[string]generatedArrow{
	"RoughArrow":         {Name: "Rough Arrow", ItemID: 2512, DPS: 1.5},
	"SharpArrow":         {Name: "Sharp Arrow", ItemID: 2515, DPS: 3.5},
	"RazorArrow":         {Name: "Razor Arrow", ItemID: 3030, DPS: 7.5},
	"FeatheredArrow":     {Name: "Feathered Arrow", ItemID: 3464, DPS: 9.5},
	"JaggedArrow":        {Name: "Jagged Arrow", ItemID: 11285, DPS: 13},
	"ExplosiveArrow":     {Name: "Explosive Arrow", ItemID: 10579, DPS: 14.5},
	"IceThreadedArrow":   {Name: "Ice Threaded Arrow", ItemID: 19316, DPS: 16.5},
	"ThoriumHeadedArrow": {Name: "Thorium Headed Arrow", ItemID: 18042, DPS: 17.5},
	"SwiftfeatherArrow":  {Name: "Swiftfeather Arrow", ItemID: 274387, DPS: 24.5},
}

// A quiver as the client's items describe it: the ranged attack speed, in percent, its equip spell
// grants. One quiver a speed, the highest item level of those that grant it.
type generatedQuiver struct {
	Name   string
	ItemID int32
	Haste  float64
}

// Keyed by the quiver's Go identifier, which is what proto.HunterOptions_QuiverBonus names it.
var quivers = map[string]generatedQuiver{
	"HuntingQuiver":             {Name: "Hunting Quiver", ItemID: 3573, Haste: 10},
	"QuiverOfTheNightWatch":     {Name: "Quiver of the Night Watch", ItemID: 3605, Haste: 11},
	"HeavyQuiver":               {Name: "Heavy Quiver", ItemID: 7371, Haste: 12},
	"QuickdrawQuiver":           {Name: "Quickdraw Quiver", ItemID: 8217, Haste: 13},
	"AncientSinewWrappedLamina": {Name: "Ancient Sinew Wrapped Lamina", ItemID: 18714, Haste: 15},
}
