// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package hunter

import (
	"github.com/wowsims/forever/sim/core/spelldata"
)

// Not generated:
//   Bat: Summoning: no hunter family teaches it

// A pet family as the client's skill lines describe it: the Tamed Pet Passive that states the
// family's damage, armor and health, and the abilities the family learns, pet side, as the
// triggered ladders of the hunter families that teach them.
type generatedPetFamily struct {
	Name      string
	Passive   spelldata.Ladder
	Abilities []spelldata.Ladder
}

// Keyed by the family's Go identifier, which is what proto.HunterOptions_PetType names it.
var petFamilies = map[string]generatedPetFamily{
	"Bat":         {Name: "Bat", Passive: spelldata.Ranked(17206), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.DiveTriggered}},
	"Bear":        {Name: "Bear", Passive: spelldata.Ranked(17208), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.ClawTriggered, spellData.DashTriggered, spellData.SwipeTriggered}},
	"BirdOfPrey":  {Name: "Bird of Prey", Passive: spelldata.Ranked(17216), Abilities: []spelldata.Ladder{spellData.ClawTriggered, spellData.DiveTriggered, spellData.MineTriggered}},
	"Boar":        {Name: "Boar", Passive: spelldata.Ranked(7000), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.ChargeTriggered, spellData.DashTriggered}},
	"CarrionBird": {Name: "Carrion Bird", Passive: spelldata.Ranked(17209), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.ClawTriggered, spellData.DemoralizingScreechTriggered, spellData.DiveTriggered}},
	"Cat":         {Name: "Cat", Passive: spelldata.Ranked(17210), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.ClawTriggered, spellData.DashTriggered, spellData.ProwlTriggered}},
	"CoreHound":   {Name: "Core Hound", Passive: spelldata.Ranked(444831), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.LavaBreathTriggered}},
	"Crab":        {Name: "Crab", Passive: spelldata.Ranked(17211), Abilities: []spelldata.Ladder{spellData.ClawTriggered, spellData.DashTriggered, spellData.PinchTriggered}},
	"Crocilisk":   {Name: "Crocilisk", Passive: spelldata.Ranked(17212), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.DashTriggered, spellData.DismemberTriggered}},
	"Fox":         {Name: "Fox", Passive: spelldata.Ranked(17223), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.DashTriggered, spellData.TrickstersDanceTriggered}},
	"Gorilla":     {Name: "Gorilla", Passive: spelldata.Ranked(17214), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.DashTriggered, spellData.ThunderstompTriggered}},
	"Hyena":       {Name: "Hyena", Passive: spelldata.Ranked(17215), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.DashTriggered, spellData.TendonRipTriggered}},
	"Raptor":      {Name: "Raptor", Passive: spelldata.Ranked(17217), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.ClawTriggered, spellData.DashTriggered, spellData.SavageRendTriggered}},
	"Scorpid":     {Name: "Scorpid", Passive: spelldata.Ranked(17218), Abilities: []spelldata.Ladder{spellData.ClawTriggered, spellData.DashTriggered, spellData.ScorpidPoisonTriggered}},
	"Spider":      {Name: "Spider", Passive: spelldata.Ranked(17219), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.DashTriggered, spellData.WebTriggered}},
	"Tallstrider": {Name: "Tallstrider", Passive: spelldata.Ranked(17220), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.DashTriggered, spellData.DustCloudTriggered}},
	"Turtle":      {Name: "Turtle", Passive: spelldata.Ranked(17221), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.DashTriggered, spellData.ShellShieldTriggered}},
	"WindSerpent": {Name: "Wind Serpent", Passive: spelldata.Ranked(17222), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.DiveTriggered, spellData.LightningBreathTriggered}},
	"Wolf":        {Name: "Wolf", Passive: spelldata.Ranked(17223), Abilities: []spelldata.Ladder{spellData.BiteTriggered, spellData.DashTriggered, spellData.FuriousHowlTriggered}},
}
